version: '3.8'

services:

  BFF:
    image: kartenspielen-bff
    container_name: kartenspielen-bff
    build:
      context: "."
      dockerfile: "docker/dev/Dockerfile"
    ports:
      - 3000:${VITE_SERVER_PORT}
    environment:
      TABLE_HOST: ${TABLE_HOST}
      TABLE_PORT: ${TABLE_SERVER_PORT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      SERVER_PORT: ${VITE_SERVER_PORT}
      NODE_OPTIONS: --max_old_space_size=8192
    volumes:
      - "./src:/app/src"
      - "./static:/app/static"
      - "./tests:/app/tests"
      - "./prisma:/app/prisma"
      - "../protos:/protos"
    networks:
      kartenspielen:
        ipv4_address: 192.168.0.5
    hostname: BFF
    extra_hosts:
      - table:192.168.0.2
      - mysql:192.168.0.3

networks:
  kartenspielen:
    name: kartenspielen
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.1/24