version: '3.8'

services:

  table-api:
    image: kartenspielen-table
    container_name: kartenspielen-table
    build:
      context: "."
      dockerfile: "docker/api/Dockerfile"
    ports:
      - 50051:${TABLE_SERVER_PORT}
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      SERVER_PORT: ${TABLE_SERVER_PORT}
    depends_on:
      - db
    volumes:
      - "./config:/app/config"
      - "./infrastructure:/app/infrastructure"
      - "./interface:/app/interface"
    networks:
      kartenspielen:
        ipv4_address: 192.168.0.2
    hostname: table
    extra_hosts:
      - mysql:192.168.0.3
    command: go run main.go

  db:
    image: mysql:8.0 # プロダクトで使うならバージョンはlatestじゃないほうが良いです
    container_name: kartenspielen-mysql
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE:  ${DB_NAME}
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 20s
        retries: 5
    ports:
      - 3307:${DB_PORT}
    volumes:
      # - ./db:/docker-entrypoint-initdb.d # コンテナ作成時に走るシェルスクリプト指定
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      kartenspielen:
        ipv4_address: 192.168.0.3
    hostname: mysql

  db-test:
    image: mysql:8.0 # プロダクトで使うならバージョンはlatestじゃないほうが良いです
    container_name: kartenspielen-mysql-test
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD_TEST}
    ports:
      - 3308:${DB_PORT_TEST}
    volumes:
      - ./server/docker/migrations:/docker-entrypoint-initdb.d # コンテナ作成時に走るシェルスクリプト指定
    networks:
      kartenspielen:
        ipv4_address: 192.168.0.6
    hostname: mysql-test

  migrate:
    image: kartenspielen-migrate
    container_name: kartenspielen-migrate
    build:
      context: "./server"
      dockerfile: "docker/migrations/Dockerfile"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      SERVER_PORT: ${TABLE_SERVER_PORT}
    volumes:
      - ./docker/migrations:/app
    networks:
      kartenspielen:
        ipv4_address: 192.168.0.4
    hostname: migrate

networks:
  kartenspielen:
    name: kartenspielen
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.1/24